# docker-compose
version: "3.8"

services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_USERNAME: alexis
      MONGO_INITDB_PASSWORD: alexis
      MONGO_INITDB_DATABASE: univ_express

  mongoku:
    image: huggingface/mongoku

    ports:
      - 27018:3100
